{% set name = "qss" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qss-{{ version }}.tar.gz
  sha256: 1e8ce6866cb6aaced39d317798a4d359d13363ae593496c514cf252bc7011d65

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy ==1.13.1
    - qdldl-python
    - cvxpy
    - matplotlib-base

test:
  imports:
    - qss
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cvxgrp/qss
  summary: 'QSS: Quadratic-Separable Solver'
  dev_url: https://github.com/cvxgrp/qss
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pluflou
